name: filescale-gRPC

services:
  generator:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - .:/workspace
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    working_dir: /workspace
