name: Validate Protocol

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate protocol files
        run: make validate
      - name: Test Go compilation
        run: make test-go
      - name: Upload generated artifacts (for debugging)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: generated-code
          path: gen/
